Sp6 584 contact refactor
devonfw-forge/wayat-flutter-python-mvp pull request #596
Opened 2022-10-03 13:48 UTC by josuecapgemini

Remove available property from Contact domain.
Update shareLocation to shareLocationTo property on Contact domain.

2022-10-03 14:06 UTC, capf4bbo requested changes

2022-10-03 14:06 UTC, capf4bbo commented on wayat/frontend/lib/domain/location/contact_location.dart
>        bool? shareLocation,
This should be shareLocationTo

2022-10-03 14:14 UTC, josuecapgemini commented on wayat/frontend/lib/domain/location/contact_location.dart
>        bool? shareLocation,
solved!

2022-10-04 06:37 UTC, capf4bbo approved these changes

2022-10-04 06:37 UTC, merged